### PR TITLE
mmu: Fix compilation issues

### PR DESCRIPTION
**Pull request by lioncash**
mmu_unmap_range was also passing the physical address.

If this is actually unnecessary and the argument itself should be removed instead, then I can just modify this change to do that instead.

### CODE REVIEW

**Comment by SciresM** [comment]
This one is, I think, probably @TuxSH's call.

**Comment by TuxSH** [comment]
I think that is unnecessary -- you don't need to know the PA to unmap a given PA.

**Comment by MerryMage** [comment]
Relateldly, there is also a `mmu_unmap_page_range` call (a function that doesn't exist) in `mmio_unmap_all_devices`.

That should likely be:
```
mmu_unmap_range(3, mmu_l3_tbl, MMIO_BASE + offset, devices[i].size);
```
instead.

**Comment by lioncash** [comment]
Amended both

**Pull request merged**
