### PR TITLE
Add missing string.h includes

### PR DESCRIPTION
**Pull request by lioncash**
Just some inclusions that were missing

### CODE REVIEW

**Comment by SciresM** [comment]
Not sure about this one -- Are we using <string.h> or rolling our own memcpy/memset? Paging @TuxSH since I think he's the person to ask.

**Comment by lioncash** [comment]
What would the benefit of rolling memcpy and memset be? (if it's for perf reasons, have any benchmarks been done to warrant it?)

**Comment by SciresM** [comment]
Per @TuxSH in private conversation: "string.h afaik, but without newlib. We'll see onceit builds"

I think I'll let this sit for now and let Tux figure out how to merge/deal with it.

**Comment by lioncash** [comment]
Sure thing, I've moved the only unrelated header change out into its own commit in #25

**Comment by SciresM** [comment]
Cool, much appreciated. Merged #25. :)

**Pull request merged**
